ALTER TABLE minions_info
ALTER COLUMN age SET NOT NULL, 
ALTER COLUMN age SET DEFAUlt 0,
ALTER COLUMN "name" SET NOT NULL,
ALTER COLUMN "name" SET DEFAUlt '',
ALTER COLUMN code SET NOT NULL,
ALTER COLUMN code SET DEFAUlt ''
;
	
